exclude_headers: [mpi.h,
                  omp.h,
                  stdint.h,
                  stdlib.h,
                  string.h,
                  stdio.h,
                  stdbool.h,
                  stdarg.h,
                  time.h,
                  math.h,
                  unistd.h,
                  sched.h,
                  glibc-sched.h,
                  stddef.h,
                  limits.h,
                  assert.h]
REPOS_ORIGIN_DIR: '/home/nadavsc/LIGHTBITS/data_gathering_script/git_repos'
REPOS_MPI_DIR: '/home/nadavsc/LIGHTBITS/code2mpi/DB/repositories_MPI'
REPOS_MPI_SLICED_DIR: '/home/nadavsc/LIGHTBITS/code2mpi/DB/repositories_MPI_SLICED'
PROGRAMS_MPI_DIR: '/home/nadavsc/LIGHTBITS/code2mpi/DB/programs'
EXTENSIONS: ['.c', '.f', '.f77', '.f90', '.f95', '.f03', '.cc', '.cpp', '.cxx', '.h']
FORTRAN_EXTENSIONS: ['.f', '.f77', '.f90', '.f95', '.f03']
