exclude_headers: [mpi.h,
                  omp.h,
                  stdint.h,
                  stdlib.h,
                  string.h,
                  stdio.h,
                  stdbool.h,
                  stdarg.h,
                  time.h,
                  math.h,
                  unistd.h,
                  sched.h,
                  glibc-sched.h,
                  stddef.h,
                  limits.h,
                  assert.h]
